# Generated by Django 2.0.1 on 2018-01-20 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
                ('upload', models.FileField(upload_to='uploads/')),
                ('descricao', models.TextField(blank=True, verbose_name='Obejtivo')),
            ],
        ),
    ]
